export const API_CALL_REQUEST = 'API_CALL_REQUEST';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';

export const OPEN_DRAWER_REQUEST = 'OPEN_DRAWER_REQUEST';
export const OPEN_DRAWER_SUCCESS = 'OPEN_DRAWER_SUCCESS';
export const CLOSE_DRAWER_REQUEST = 'CLOSE_DRAWER_REQUEST';
export const CLOSE_DRAWER_SUCCESS = 'CLOSE_DRAWER_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const TOKEN_UNVALID = 'TOKEN_UNVALID';

export const ADD_PROFESSOR_REQUEST = 'ADD_PROFESSOR_REQUEST';
export const ADD_PROFESSOR_SUCCESS = 'ADD_PROFESSOR_SUCCESS';
export const ADD_PROFESSOR_ERROR = 'ADD_PROFESSOR_ERROR';

export const GET_USER_INFOS = 'GET_USER_INFOS';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const GET_STUDENTS_REQUEST = 'GET_STUDENTS_REQUEST';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_ERROR = 'GET_STUDENTS_ERROR';
export const GET_STUDENTSNBR_REQUEST = 'GET_STUDENTS_REQUEST';
export const GET_STUDENTNBR = 'GET_STUDENTNBR';

export const GET_IMG_REQUEST = 'GET_IMG_REQUEST';
export const GET_IMG_RESPONSE = 'DET_IMG_RESPONSE';
export const EMPTY_IMG_REQUEST = 'EMPTY_IMG_REQUEST';
export const UPLOAD_IMG_REQUEST = 'GET_IMG_SUCCESS';

export const SNACK_PUT_ERROR = 'SNACK_PUT_ERROR';
export const SNACK_PUT_SUCCESS = 'SNACK_PUT_SUCCESS';
export const SNACK_PUT_REQUEST = 'SNACK_PUT_REQUEST';
export const SNACK_RESET = 'SNACK_RESET';

export const UPDATE_PROF_REQUEST = 'UPDATE_PROF_REQUEST';
export const UPDATE_PROF_SUCCESS = 'UPDATE_PROF_SUCCESS';
export const UPDATE_PROF_ERROR = 'UPDATE_PROF_ERROR';

export const VERIFY_TOKEN_REQUEST = 'VERIFY_TOKEN_REQUEST';

export const STUDENT_PROFILE_REQUEST = 'STUDENT_PROFILE_REQUEST';
export const STUDENT_PROFILE_SUCCESS = 'STUDENT_PROFILE_SUCCESS';
export const STUDENT_PROFILE_ERROR = 'STUDENT_PROFILE_ERROR';

export const GET_CLASSES_REQUEST = 'GET_CLASSES_REQUEST';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';

export const GET_APPS_BUY_REQUEST = 'GET_APPS_BUY_REQUEST';
export const GET_APPS_BUY_SUCCESS = 'GET_APPS_BUY_SUCCESS';
export const GET_APPS_BUY_ERROR = 'GET_APPS_BUY_ERROR';

export const GET_APPNBR_REQUEST = 'GET_APPNBR_REQUEST';
export const GET_APPNBR = 'GET_APPNBR';

export const CHANGE_IDENTI_REQUEST = 'CHANGE_IDENTI_REQUEST';

export const LOADING = 'LOADING';
export const END_LOADING = 'END_LOADING';

export const CHANGE_PASS_REQUEST = 'CHANGE_PASS_REQUEST';

export const GET_APP_REQUEST = 'GET_APP_REQUEST';
export const GET_APP_SUCCESS = 'GET_APP_SUCCESS';
export const GET_APP_ERROR = 'GET_APP_ERROR';

export const GET_APP_REGISTRED_SUCCESS = 'GET_APP_REGISTRED_SUCCESS';
export const GET_APP_REGISTRED_ERROR = 'GET_APP_REGISTRED_ERROR';

export const ASK_APP_REQUEST = 'ASK_APP_REQUEST';
export const BUY_APP_REQUEST = 'BUY_APP_REQUEST';

export const GET_NOTIFS_REQUEST = 'GET_NOTIFS_REQUEST';
export const GET_NOTIFS_SUCCESS = 'GET_NOTIFS_SUCCESS';
export const GET_NOTIFS_ERROR = 'GET_NOTIFS_ERROR';

export const SHOW_NOTIF_REQUEST = 'SHOW_NOTIF_REQUEST';
export const SHOW_NOTIF_SUCCESS = 'SHOW_NOTIF_SUCCESS';
export const SHOW_NOTIF_ERROR = 'SHOW_NOTIF_ERROR';
export const SHOW_NOTIF_RESET = 'SHOW_NOTIF_RESET';
export const NOTIFS_DASH_STOP = 'NOTIFS_DASH_STOP';

export const RELOAD_REQUEST = 'RELOAD_REQUEST';
export const STOP_RELOAD = 'STOP_RELOAD';

export const SHOW_DASH_TMP_STOP = 'SHOW_DASH_TMP_STOP';

export const ADD_AVIS_REQUEST = 'ADD_AVIS_REQUEST';
export const ADD_AVIS_SUCCESS = 'ADD_AVIS_SUCCESS';
export const ADD_AVIS_ERROR = 'ADD_AVIS_ERROR';

export const GET_AVIS_REQUEST = 'GET_AVIS_REQUEST';
export const GET_AVIS_SUCCESS = 'GET_AVIS_SUCCESS';
export const GET_AVIS_ERROR = 'GET_AVIS_ERROR';

export const GET_NB_AVIS_REQUEST = 'GET_NB_AVIS_REQUEST';
export const GET_NB_AVIS_SUCCESS = 'GET_NB_AVIS_SUCCESS';
export const GET_NB_AVIS_ERROR = 'GET_NB_AVIS_ERROR';

export const GET_LAST_AVIS_NBR = 'GET_LAST_AVIS_NBR';
export const GET_USERAVIS_SUCCESS = 'GET_USERAVIS_SUCCESS';

export const UPDATE_AVIS_REQUEST = 'UPDATE_AVIS_REQUEST';

export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';

export const GET_FILES_REQUEST = 'GET_FILES_REQUEST';
export const GET_FILES_SUCCESS = 'GET_FILES_SUCCESS';
export const GET_FILES_ERROR = 'GET_FILES_ERROR';

export const STUDENT_RESULTS_REQUEST = 'STUDENT_RESULTS_REQUEST';
export const STUDENT_RESULTS_SUCCESS = 'STUDENT_RESULTS_SUCCESS';
export const STUDENT_RESULTS_ERROR = 'STUDENT_RESULTS_ERROR';

export const UPDATE_FILE = 'UPDATE_FILE';
export const DELETE_FILE = 'DELETE_FILE';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';

export const RELOAD_PAGE = 'RELOAD_PAGE';

export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';

export const ABO_POPUP_OPEN = "ABO_POPUP_OPEN";
export const ABO_POPUP_CLOSE = "ABO_POPUP_CLOSE";
export const GET_SUB_INFO_REQUEST = "GET_SUB_INFO_REQUEST";
export const GET_SUB_INFO_SUCCESS = "GET_SUB_INFO_SUCCESS";
export const GET_SUB_INFO_ERROR = "GET_SUB_INFO_ERROR";
export const SUBSCRIBE_ABO_REQUEST = "SUBSCRIBE_ABO_REQUEST";

export const ACCESS_PAYMENT_INFOS_REQUEST = 'ACCESS_PAYMENT_INFOS_REQUEST';
export const ACCESS_PAYMENT_INFOS_SUCCESS = 'ACCESS_PAYMENT_INFOS_SUCCESS';
export const PASS_POPUP_OPEN = 'PASS_POPUP_OPEN';
export const PASS_POPUP_CLOSE = 'PASS_POPUP_CLOSE';

export const SUBMIT_IBAN_REQUEST = "SUBMIT_IBAN_REQUEST";
export const SUBMIT_IBAN_SUCCESS = "SUBMIT_IBAN_SUCCESS";

//STRIPE PAYMENTS
export const ADD_METHOD_REQUEST = "ADD_METHOD_REQUEST";
export const ADD_METHOD_LOADING = "ADD_METHOD_REQUEST";
export const ADD_METHOD_SUCCESS = "ADD_METHOD_SUCCESS";
export const ADD_METHOD_ERROR = "ADD_METHOD_ERROR";

export const SEND_MESSAGE = "SEND_MESSAGE";
