export const GET_PROFESSOR = 'GET_PROFESSOR';
export const RECEIVE_PROFESSOR = 'RECEIVE_PROFESSOR';

export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

export const OPEN_DRAWER_REQUEST = "OPEN_DRAWER_REQUEST";
export const OPEN_DRAWER_SUCCESS = "OPEN_DRAWER_SUCCESS";
export const CLOSE_DRAWER_REQUEST = "CLOSE_DRAWER_REQUEST";
export const CLOSE_DRAWER_SUCCESS = "CLOSE_DRAWER_SUCCESS";

