export const GET_PROFESSOR = 'GET_PROFESSOR';
export const RECEIVE_PROFESSOR = 'RECEIVE_PROFESSOR';

export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

export const OPEN_DRAWER_REQUEST = "OPEN_DRAWER_REQUEST";
export const OPEN_DRAWER_SUCCESS = "OPEN_DRAWER_SUCCESS";
export const CLOSE_DRAWER_REQUEST = "CLOSE_DRAWER_REQUEST";
export const CLOSE_DRAWER_SUCCESS = "CLOSE_DRAWER_SUCCESS";

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const ADD_PROFESSOR_REQUEST = 'ADD_PROFESSOR_REQUEST';
export const ADD_PROFESSOR_SUCCESS = "ADD_PROFESSOR_SUCCESS";
export const ADD_PROFESSOR_ERROR = "ADD_PROFESSOR_ERROR";

export const GET_USER_INFOS = "GET_USER_INFOS";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_ERROR = "GET_STUDENTS_ERROR";

export const GET_IMG_REQUEST = "GET_IMG_REQUEST";
export const GET_IMG_RESPONSE = "DET_IMG_RESPONSE";
export const EMPTY_IMG_REQUEST = "EMPTY_IMG_REQUEST";

export const SNACK_PUT_ERROR = 'SNACK_PUT_ERROR';
export const SNACK_PUT_SUCCESS = 'SNACK_PUT_SUCCESS';
export const SNACK_PUT_REQUEST = 'SNACK_PUT_REQUEST';

export const UPDATE_PROF_REQUEST = 'UPDATE_PROF_REQUEST';
export const UPDATE_PROF_SUCCESS = 'UPDATE_PROF_SUCCESS';
export const UPDATE_PROF_ERROR = 'UPDATE_PROF_ERROR';



